name: Setup Swift
description: "Set up a specific version of Swift and add the command-line tools to the PATH."
author: Junfeng Zhang
inputs:
  swift-version: 
    description: "Exact version of Swift to use."
    required: true
  architecture:
    description: "The target architecture of the Swift interpreter."
outputs:
  swift-version:
    description: "The installed Swift version."
  swift-path:
    description: "The absolute path to the Swift executable."
runs:
  using: 'node16'
  main: 'dist/setup/index.js'