name: "Setup Swift environment"
description: "Set up a specific version of Swift and add the command-line tools to the PATH."
author: "Junfeng Zhang"
inputs:
  swift-version: 
    description: "Version spec of the version to use. Examples: 5.9, swift-5.10-RELEASE, nightly-6.0."
    required: true
outputs:
  swift-version:
    description: "The installed Swift version."
  swift-path:
    description: "The path to the Swift executable."
runs:
  using: "node20"
  main: "dist/setup/index.js"