name: Pull Request Validation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  unit-test:
    name: Unit tests
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/checkout@v3

      - run: |
          yarn install
          yarn run format-check
          yarn test

  integration-test:
    name: Install Swift ${{ matrix.swift-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift-version: ["5.7"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: |
          yarn install
          yarn build

      - name: Run swift --version if available
        if: runner.os == 'macOS' || runner.os == 'Linux'
        run: |
          if which swift >/dev/null; then
            swift --version
          fi

      - name: Run swift-setup...
        uses: ./
        with:
          swift-version: ${{ matrix.swift-version }}

      - run: swift --version | grep ${{ matrix.swift-version }} || exit 1

      - name: Run xcrun swift --version
        if: runner.os == 'macOS'
        run: xcrun swift --version | grep ${{ matrix.swift-version }} || exit 1

      - uses: mxschmitt/action-tmate@v3
        with:
          sudo: false
