name: Pull Request Validation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: yarn install
    - run: yarn run format-check
    - run: yarn test
  integration-test:
    name: Integrate Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.7"]
    steps:
    - uses: actions/checkout@v3
    - run: yarn install
    - run: yarn build
    - uses: ./
      with:
        swift-version: ${{ matrix.swift }}
    - name: Print Swift version
      run: swift --version

    - name: Swift version
      run: swift --version | grep ${{ matrix.swift }} || exit 1
