name: integration-tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  releases:
    name: setup releases versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift-version: ["swift-5.7.1-RELEASE", "5.7.1"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Swift ${{ matrix.swift-version }}
        uses: ./
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Verify swift --version and xcrun swift --version
        run: __tests__/verify-swift.sh "${{ matrix.swift-version }}"
        shell: bash

  mainline-development-snapshots:
    name: setup mainline development snapshots
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        # Because we don't know the version number corresponding to the "swift-version", 
        # so we hardcode the matching version for test.
        # If you want to update this version you should also change expect version for test run.
        swift-version: ["swift-DEVELOPMENT-SNAPSHOT-2022-11-11-a"]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Swift ${{ matrix.swift-version }}
      uses: ./
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: Verify swift --version and xcrun swift --version
      run: __tests__/verify-swift.sh "5.8-dev"
      shell: bash

  development-snapshots:
    name: setup development snapshots
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift-version: ["swift-5.7-DEVELOPMENT-SNAPSHOT-2022-10-03-a"]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Swift ${{ matrix.swift-version }}
      uses: ./
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: Verify swift --version and xcrun swift --version if possible
      run: __tests__/verify-swift.sh "${{ matrix.swift-version }}"
      shell: bash