name: integration-tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  integration-tests:
    name: setup swift on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Run setup-swift (5)
        uses: ./
        with:
          swift-version: "5"
      - name: Verify swift (5)
        run: __tests__/verify-swift.sh "5.10"
        shell: bash

      - name: Run setup-swift (5.10)
        uses: ./
        with:
          swift-version: "5.10"
      - name: Verify swift (5.10)
        run: __tests__/verify-swift.sh "5.10"
        shell: bash
      
      - name: Run setup-swift (swift-5.10-RELEASE)
        uses: ./
        with:
          swift-version: "swift-5.10-RELEASE"
      - name: Verify swift (swift-5.10-RELEASE)
        run: __tests__/verify-swift.sh "5.10"
        shell: bash
      
      - name: Run setup-swift (nightly-6.0)
        uses: ./
        with:
          swift-version: "nightly-6.0"
      - name: Verify swift (nightly-6.0)
        run: __tests__/verify-swift.sh "nightly-6.0"
        shell: bash

      - name: Run setup-swift (swift-6.0-DEVELOPMENT-SNAPSHOT-2024-04-20-a)
        uses: ./
        with:
          swift-version: "swift-6.0-DEVELOPMENT-SNAPSHOT-2024-04-20-a"
      - name: Verify swift (swift-6.0-DEVELOPMENT-SNAPSHOT-2024-04-20-a)
        run: __tests__/verify-swift.sh "swift-6.0-DEVELOPMENT-SNAPSHOT-2024-04-20-a"
        shell: bash

      - name: Run setup-swift (nightly)
        uses: ./
        with:
          swift-version: "nightly"
      - name: Verify swift (nightly)
        run: __tests__/verify-swift.sh "^[0-9]+\.[0-9]+(\.[0-9]+)?-dev$" 
        shell: bash

      - name: Run setup-swift (nightly-main)
        uses: ./
        with:
          swift-version: "nightly-main"
      - name: Verify swift (nightly-main)
        run: __tests__/verify-swift.sh "^[0-9]+\.[0-9]+(\.[0-9]+)?-dev$" 
        shell: bash

      - name: Run setup-swift (swift-DEVELOPMENT-SNAPSHOT-2023-04-11-a)
        uses: ./
        with:
          swift-version: "swift-DEVELOPMENT-SNAPSHOT-2023-04-11-a"
      - name: Verify swift (swift-DEVELOPMENT-SNAPSHOT-2023-04-11-a)
        run: __tests__/verify-swift.sh "^[0-9]+\.[0-9]+(\.[0-9]+)?-dev$" 
        shell: bash
