name: integration-tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  integration-tests:
    name: setup swift on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Run setup-swift (5)
        uses: ./
        with:
          swift-version: "5"
      - name: Verify swift (5)
        run: __tests__/verify-swift.sh "5.10.1"
        shell: bash

      - name: Run setup-swift (5.10)
        uses: ./
        with:
          swift-version: "5.10"
      - name: Verify swift (5.10)
        run: __tests__/verify-swift.sh "5.10.1"
        shell: bash
      
      - name: Run setup-swift (swift-5.10.1-RELEASE)
        uses: ./
        with:
          swift-version: "swift-5.10.1-RELEASE"
      - name: Verify swift (swift-5.10.1-RELEASE)
        run: __tests__/verify-swift.sh "5.10.1"
        shell: bash
      
      - name: Run setup-swift (nightly-main)
        uses: ./
        with:
          swift-version: "nightly-main"
      - name: Verify swift (nightly-main)
        run: __tests__/verify-swift.sh "^[0-9]+\.[0-9]+(\.[0-9]+)?-dev$" 
        shell: bash
