name: integration-tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  releases:
    name: setup releases versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift-version: ["swift-5.7.1-RELEASE"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Swift ${{ matrix.swift-version }}
        uses: ./
        with:
          swift-version: ${{ matrix.swift-version }}
      - name: Verify swift --version and xcrun swift --version
        run: __tests__/verify-swift.sh "${{ matrix.swift-version }}"
        shell: bash

  development-snapshots:
    name: setup development snapshots
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift-version: ["nightly-5.7", "swift-5.7-DEVELOPMENT-SNAPSHOT-2022-10-03-a"]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Swift ${{ matrix.swift-version }}
      uses: ./
      with:
        swift-version: ${{ matrix.swift-version }}
    - name: Verify swift --version and xcrun swift --version if possible
      run: __tests__/verify-swift.sh "${{ matrix.swift-version }}"
      shell: bash